import type {BackendRole} from './auth';
export type Field={key:string;label:string;type?:'text'|'number'|'date'|'datetime'|'textarea'|'select'|'json'|'csv'|'lookup';options?:string[];lookup?:string;lookupLabel?:string;required?:boolean};export type Resource={title:string;description:string;endpoint:string;createEndpoint?:string;columns:{key:string;label:string}[];fields:Field[];createRoles?:BackendRole[];editRoles?:BackendRole[];deleteRoles?:BackendRole[]};
const staff:BackendRole[]=['SCHOOL_ADMIN'],admins:BackendRole[]=['ADMINISTRATOR','SCHOOL_ADMIN'],teach:BackendRole[]=['SCHOOL_ADMIN','TEACHER'];const session:Field={key:'academicSessionId',label:'Academic session',type:'lookup',lookup:'/academics/sessions',lookupLabel:'name',required:true},cls:Field={key:'classId',label:'Class',type:'lookup',lookup:'/academics/classes',lookupLabel:'name',required:true},sec:Field={key:'sectionId',label:'Section',type:'lookup',lookup:'/academics/sections',lookupLabel:'name',required:true},sub:Field={key:'subjectId',label:'Subject',type:'lookup',lookup:'/academics/subjects',lookupLabel:'name',required:true};
export const resources:Record<string,Resource>={
 schools:{title:'Schools',description:'Assigned school workspaces.',endpoint:'/schools',columns:[{key:'name',label:'School'},{key:'code',label:'Code'},{key:'status',label:'Status'}],fields:[{key:'name',label:'Name',required:true},{key:'code',label:'Code',required:true},{key:'slug',label:'Slug',required:true},{key:'board',label:'Board'}],editRoles:['ADMINISTRATOR']},
 'school-admins':{title:'School Admins',description:'Manage school administrator accounts.',endpoint:'/users?role=SCHOOL_ADMIN',createEndpoint:'/onboarding/school-admin',columns:[{key:'name',label:'Name'},{key:'email',label:'Email'},{key:'status',label:'Status'}],fields:[{key:'name',label:'Name',required:true},{key:'email',label:'Email',required:true},{key:'password',label:'Password',required:true},{key:'phone',label:'Phone'}],createRoles:['ADMINISTRATOR'],editRoles:['ADMINISTRATOR']},
 sessions:{title:'Academic Sessions',description:'Create sessions and set the current academic year.',endpoint:'/academics/sessions',columns:[{key:'name',label:'Session'},{key:'status',label:'Status'},{key:'isCurrent',label:'Current'}],fields:[{key:'name',label:'Name',required:true},{key:'startsAt',label:'Starts',type:'date',required:true},{key:'endsAt',label:'Ends',type:'date',required:true},{key:'status',label:'Status',type:'select',options:['PLANNED','ACTIVE','CLOSED']}],createRoles:staff,editRoles:staff,deleteRoles:staff},
 students:{title:'Students',description:'Admissions, profile and class allocation.',endpoint:'/students',createEndpoint:'/onboarding/student',columns:[{key:'firstName',label:'First name'},{key:'lastName',label:'Last name'},{key:'admissionNo',label:'Admission No.'},{key:'rollNo',label:'Roll No.'},{key:'status',label:'Status'}],fields:[{key:'firstName',label:'First name',required:true},{key:'lastName',label:'Last name'},{key:'email',label:'Login email',required:true},{key:'password',label:'Password',required:true},{key:'admissionNo',label:'Admission no.',required:true},{key:'rollNo',label:'Roll no.'},session,cls,sec,{key:'phone',label:'Phone'}],createRoles:staff,editRoles:staff,deleteRoles:staff},
 teachers:{title:'Teachers',description:'Faculty profiles and allocations.',endpoint:'/teachers',createEndpoint:'/onboarding/teacher',columns:[{key:'name',label:'Teacher'},{key:'employeeCode',label:'Employee Code'},{key:'department',label:'Department'},{key:'status',label:'Status'}],fields:[{key:'name',label:'Name',required:true},{key:'email',label:'Email',required:true},{key:'password',label:'Password',required:true},{key:'employeeCode',label:'Employee code',required:true},{key:'department',label:'Department'},{key:'phone',label:'Phone'}],createRoles:staff,editRoles:staff,deleteRoles:staff},
 classes:{title:'Classes',description:'Classes for the active academic session.',endpoint:'/academics/classes',columns:[{key:'name',label:'Class'},{key:'numericOrder',label:'Order'},{key:'status',label:'Status'}],fields:[session,{key:'name',label:'Name',required:true},{key:'numericOrder',label:'Order',type:'number'}],createRoles:staff,editRoles:staff,deleteRoles:staff},
 sections:{title:'Sections',description:'Class sections, rooms and capacities.',endpoint:'/academics/sections',columns:[{key:'name',label:'Section'},{key:'room',label:'Room'},{key:'capacity',label:'Capacity'},{key:'status',label:'Status'}],fields:[session,cls,{key:'name',label:'Name',required:true},{key:'room',label:'Room'},{key:'capacity',label:'Capacity',type:'number'}],createRoles:staff,editRoles:staff,deleteRoles:staff},
 subjects:{title:'Subjects',description:'Subjects and academic mappings.',endpoint:'/academics/subjects',columns:[{key:'name',label:'Subject'},{key:'code',label:'Code'},{key:'type',label:'Type'},{key:'status',label:'Status'}],fields:[session,{key:'name',label:'Name',required:true},{key:'code',label:'Code',required:true},{key:'type',label:'Type',type:'select',options:['CORE','ELECTIVE','PRACTICAL','ACTIVITY']}],createRoles:staff,editRoles:staff,deleteRoles:staff},
 timetable:{title:'Timetable',description:'Weekly class schedule.',endpoint:'/timetable',columns:[{key:'day',label:'Day'},{key:'classId',label:'Class'},{key:'sectionId',label:'Section'},{key:'published',label:'Published'}],fields:[session,cls,sec,{key:'day',label:'Day',type:'select',options:['MONDAY','TUESDAY','WEDNESDAY','THURSDAY','FRIDAY','SATURDAY']},{key:'periods',label:'Periods JSON',type:'json'}],createRoles:staff,editRoles:staff,deleteRoles:staff},
 fees:{title:'Fees & Payments',description:'Fee structures, dues and payments.',endpoint:'/fees',columns:[{key:'name',label:'Fee'},{key:'category',label:'Category'},{key:'amount',label:'Amount'},{key:'dueAt',label:'Due'}],fields:[session,{key:'name',label:'Name',required:true},{key:'category',label:'Category',type:'select',options:['TUITION','TRANSPORT','EXAM','LIBRARY','ADMISSION','OTHER']},{key:'classId',label:'Class',type:'lookup',lookup:'/academics/classes',lookupLabel:'name'},{key:'amount',label:'Amount',type:'number',required:true},{key:'dueAt',label:'Due date',type:'date'}],createRoles:staff,editRoles:staff,deleteRoles:staff},
 examinations:{title:'Examinations',description:'Exam schedules and assessment structures.',endpoint:'/examinations',columns:[{key:'name',label:'Exam'},{key:'type',label:'Type'},{key:'startsAt',label:'Starts'},{key:'status',label:'Status'}],fields:[session,{key:'name',label:'Name',required:true},{key:'type',label:'Type',type:'select',options:['UNIT_TEST','MID_TERM','FINAL','PRACTICAL','OTHER']},{key:'classIds',label:'Class IDs',type:'csv'},{key:'subjects',label:'Subjects JSON',type:'json'},{key:'startsAt',label:'Starts',type:'date'},{key:'endsAt',label:'Ends',type:'date'}],createRoles:staff,editRoles:staff,deleteRoles:staff},
 exams:{title:'Examinations',description:'Your examination schedule.',endpoint:'/examinations',columns:[{key:'name',label:'Exam'},{key:'type',label:'Type'},{key:'startsAt',label:'Starts'},{key:'status',label:'Status'}],fields:[]},
 results:{title:'Results',description:'Academic results and performance.',endpoint:'/results',columns:[{key:'examinationId',label:'Exam'},{key:'studentId',label:'Student'},{key:'percentage',label:'Percentage'},{key:'grade',label:'Grade'},{key:'published',label:'Published'}],fields:[session,{key:'examinationId',label:'Exam',type:'lookup',lookup:'/examinations',lookupLabel:'name',required:true},{key:'studentId',label:'Student',type:'lookup',lookup:'/students',lookupLabel:'firstName',required:true},cls,sec,{key:'marks',label:'Marks JSON',type:'json'}],createRoles:teach,editRoles:teach},
 marks:{title:'Marks Entry',description:'Enter and publish student results.',endpoint:'/results',columns:[{key:'studentId',label:'Student'},{key:'examinationId',label:'Exam'},{key:'percentage',label:'Percentage'},{key:'published',label:'Published'}],fields:[session,{key:'examinationId',label:'Exam',type:'lookup',lookup:'/examinations',lookupLabel:'name',required:true},{key:'studentId',label:'Student',type:'lookup',lookup:'/students',lookupLabel:'firstName',required:true},cls,sec,{key:'marks',label:'Marks JSON',type:'json'}],createRoles:['TEACHER'],editRoles:['TEACHER']},
 assignments:{title:'Assignments',description:'Assignments, submissions and deadlines.',endpoint:'/assignments?type=ASSIGNMENT',columns:[{key:'title',label:'Title'},{key:'subjectId',label:'Subject'},{key:'dueAt',label:'Due'},{key:'status',label:'Status'}],fields:[session,cls,{...sec,required:false},sub,{key:'title',label:'Title',required:true},{key:'description',label:'Description',type:'textarea'},{key:'type',label:'Type',type:'select',options:['ASSIGNMENT']},{key:'dueAt',label:'Due',type:'datetime'},{key:'status',label:'Status',type:'select',options:['DRAFT','PUBLISHED','CLOSED']}],createRoles:teach,editRoles:teach,deleteRoles:teach},
 homework:{title:'Homework',description:'Homework and completion tracking.',endpoint:'/assignments?type=HOMEWORK',columns:[{key:'title',label:'Homework'},{key:'subjectId',label:'Subject'},{key:'dueAt',label:'Due'},{key:'status',label:'Status'}],fields:[session,cls,{...sec,required:false},sub,{key:'title',label:'Title',required:true},{key:'description',label:'Description',type:'textarea'},{key:'type',label:'Type',type:'select',options:['HOMEWORK']},{key:'dueAt',label:'Due',type:'datetime'},{key:'status',label:'Status',type:'select',options:['DRAFT','PUBLISHED','CLOSED']}],createRoles:['TEACHER'],editRoles:['TEACHER'],deleteRoles:['TEACHER']},
 notices:{title:'Notices',description:'School announcements and updates.',endpoint:'/notices',columns:[{key:'title',label:'Notice'},{key:'priority',label:'Priority'},{key:'publishedAt',label:'Published'}],fields:[{key:'title',label:'Title',required:true},{key:'body',label:'Message',type:'textarea',required:true},{key:'audience',label:'Audience',type:'csv'},{key:'priority',label:'Priority',type:'select',options:['NORMAL','IMPORTANT','URGENT']}],createRoles:admins,editRoles:admins,deleteRoles:admins},
 calendar:{title:'Academic Calendar',description:'Holidays, events, PTMs and exams.',endpoint:'/calendar',columns:[{key:'title',label:'Event'},{key:'type',label:'Type'},{key:'startsAt',label:'Starts'}],fields:[{key:'title',label:'Title',required:true},{key:'description',label:'Description',type:'textarea'},{key:'type',label:'Type',type:'select',options:['HOLIDAY','EXAM','EVENT','PTM','ACTIVITY','OTHER']},{key:'startsAt',label:'Starts',type:'datetime',required:true},{key:'endsAt',label:'Ends',type:'datetime'},{key:'audience',label:'Audience',type:'csv'}],createRoles:staff,editRoles:staff,deleteRoles:staff},
 leave:{title:'Leave Management',description:'Leave requests and approvals.',endpoint:'/leaves',columns:[{key:'type',label:'Type'},{key:'startsAt',label:'Starts'},{key:'endsAt',label:'Ends'},{key:'status',label:'Status'}],fields:[{key:'type',label:'Type',type:'select',options:['SICK','CASUAL','EMERGENCY','OTHER']},{key:'startsAt',label:'Starts',type:'date',required:true},{key:'endsAt',label:'Ends',type:'date',required:true},{key:'reason',label:'Reason',type:'textarea',required:true}],createRoles:['TEACHER','STUDENT','PARENT']},
 children:{title:'My Children',description:'Linked child profiles.',endpoint:'/students',columns:[{key:'firstName',label:'First name'},{key:'lastName',label:'Last name'},{key:'admissionNo',label:'Admission No.'},{key:'status',label:'Status'}],fields:[]},
 certificates:{title:'Certificates & TC',description:'Request and issue school certificates.',endpoint:'/certificates',columns:[{key:'type',label:'Type'},{key:'studentId',label:'Student'},{key:'status',label:'Status'},{key:'certificateNo',label:'Certificate No.'}],fields:[{key:'studentId',label:'Student',type:'lookup',lookup:'/students',lookupLabel:'firstName'},{key:'type',label:'Type',type:'select',options:['BONAFIDE','TRANSFER_CERTIFICATE','CHARACTER','ID_CARD','OTHER'],required:true},{key:'reason',label:'Reason',type:'textarea'}],createRoles:['STUDENT','PARENT'],editRoles:[]}
};
