const base = {
  User: require('../modules/users/user.model'),
  School: require('../modules/schools/school.model'),
  Administrator: require('../modules/administrators/administrator.model'),
  AcademicSession: require('../modules/academics/academicSession.model'),
  Class: require('../modules/academics/class.model'),
  Section: require('../modules/academics/section.model'),
  Subject: require('../modules/academics/subject.model'),
  Student: require('../modules/students/student.model'),
  Parent: require('../modules/parents/parent.model'),
  Teacher: require('../modules/teachers/teacher.model'),
  Attendance: require('../modules/attendance/attendance.model'),
  Timetable: require('../modules/timetable/timetable.model'),
  Assignment: require('../modules/assignments/assignment.model'),
  Examination: require('../modules/examinations/examination.model'),
  Result: require('../modules/results/result.model'),
  Fee: require('../modules/fees/fee.model'),
  Payment: require('../modules/fees/payment.model'),
  Notice: require('../modules/notices/notice.model'),
  Leave: require('../modules/leaves/leave.model'),
  Notification: require('../modules/notifications/notification.model'),
  AuditLog: require('../modules/audit/auditLog.model'),
};
module.exports = { ...base, ...require('./extended') };
