const base = {
  User: require('../modules/users/user.model'),
  School: require('../modules/schools/school.model'),
  Administrator: require('../modules/administrators/administrator.model'),
  AcademicSession: require('../modules/academics/academicSession.model'),
  Class: require('../modules/academics/class.model'),
  Section: require('../modules/academics/section.model'),
  Subject: require('../modules/academics/subject.model'),
  Student: require('../modules/students/student.model'),
  Parent: require('../modules/parents/parent.model'),
  Teacher: require('../modules/teachers/teacher.model'),
  Attendance: require('../modules/attendance/attendance.model'),
  Timetable: require('../modules/timetable/timetable.model'),
  Assignment: require('../modules/assignments/assignment.model'),
  Examination: require('../modules/examinations/examination.model'),
  Result: require('../modules/results/result.model'),
  Fee: require('../modules/fees/fee.model'),
  Payment: require('../modules/fees/payment.model'),
  Notice: require('../modules/notices/notice.model'),
  Leave: require('../modules/leaves/leave.model'),
  Notification: require('../modules/notifications/notification.model'),
  AuditLog: require('../modules/audit/auditLog.model'),
  
  // Relocated models
  AuthSession: require('../modules/auth/authSession.model'),
  Enrollment: require('../modules/students/enrollment.model'),
  AssignmentSubmission: require('../modules/submissions/assignmentSubmission.model'),
  CalendarEvent: require('../modules/calendar/calendarEvent.model'),
  Certificate: require('../modules/certificates/certificate.model'),
  OnlinePaymentIntent: require('../modules/payments/onlinePaymentIntent.model'),
  Plan: require('../modules/plans/plan.model'),
  ModuleCatalog: require('../modules/modules/moduleCatalog.model'),
  Subscription: require('../modules/subscriptions/subscription.model'),
  SupportTicket: require('../modules/support/supportTicket.model'),
  SchoolPreference: require('../modules/school-preferences/schoolPreference.model'),
  PlatformSetting: require('../modules/platform-settings/platformSetting.model'),
};
module.exports = base;
