const mongoose = require('mongoose');
const config = require('./config/env');
const M = require('./models');
const { ROLES } = require('./constants/roles');
const ApiError = require('./utils/apiError');
const asyncHandler = require('./utils/asyncHandler');
const { success } = require('./utils/apiResponse');
const page = require('./utils/pagination');
const { accessToken, refreshToken, verifyRefresh } = require('./utils/tokens');
const authenticate = require('./middleware/auth.middleware');
const allowRoles = require('./middleware/role.middleware');
const permission = require('./middleware/permission.middleware');
const tenant = require('./middleware/tenant.middleware');
const errorHandler = require('./middleware/error.middleware');

function cookies(req){return Object.fromEntries(String(req.headers.cookie||'').split(';').map(x=>x.trim()).filter(Boolean).map(part=>{const i=part.indexOf('=');return[decodeURIComponent(i>=0?part.slice(0,i):part),decodeURIComponent(i>=0?part.slice(i+1):'')]}));}
function setRefreshCookie(res,token){res.cookie(config.cookieName,token,{httpOnly:true,secure:config.cookieSecure,sameSite:config.cookieSameSite,path:'/api/v1/auth',maxAge:7*24*60*60*1000});}
function clearRefreshCookie(res){res.clearCookie(config.cookieName,{httpOnly:true,secure:config.cookieSecure,sameSite:config.cookieSameSite,path:'/api/v1/auth'});}
function ids(v=[]){return v.map(x=>String(x?._id||x)).filter(Boolean);}
function teacherAssignmentIds(profile){const a=profile?.classAssignments||[];return{classes:ids(a.map(x=>x.classId)),sections:ids(a.map(x=>x.sectionId)),subjects:ids(a.map(x=>x.subjectId))};}
function scoped(req,resource,base={}){const r=req.user.role,s=req.studentProfile,children=req.parentProfile?.studentIds||[],ta=teacherAssignmentIds(req.teacherProfile);if([ROLES.SUPER_ADMIN,ROLES.ADMINISTRATOR,ROLES.SCHOOL_ADMIN].includes(r))return base;if(resource==='Student'){if(r===ROLES.STUDENT)return{...base,userId:req.user._id};if(r===ROLES.PARENT)return{...base,_id:{$in:ids(children)}};if(r===ROLES.TEACHER)return{...base,sectionId:{$in:ta.sections}}}if(resource==='Class'&&r===ROLES.TEACHER)return{...base,_id:{$in:ta.classes}};if(resource==='Section'&&r===ROLES.TEACHER)return{...base,_id:{$in:ta.sections}};if(resource==='Subject'&&r===ROLES.TEACHER)return{...base,_id:{$in:ta.subjects}};if(['Attendance','Result','Payment'].includes(resource)){if(r===ROLES.STUDENT&&s)return{...base,studentId:s._id};if(r===ROLES.PARENT)return{...base,studentId:{$in:ids(children)}};if(r===ROLES.TEACHER)return{...base,sectionId:{$in:ta.sections}}}if(resource==='Certificate'){if(r===ROLES.STUDENT&&s)return{...base,studentId:s._id};if(r===ROLES.PARENT)return{...base,studentId:{$in:ids(children)}};if(r===ROLES.TEACHER)return{...base,_id:{$in:[]}}}if(resource==='Fee'){if(r===ROLES.STUDENT&&s)return{...base,$or:[{studentId:s._id},{studentId:null,classId:s.classId}]};if(r===ROLES.PARENT)return{...base,$or:[{studentId:{$in:ids(children)}},{studentId:null,classId:{$in:ids(children.map(x=>x.classId))}}]}}if(['Assignment','Timetable'].includes(resource)){if(r===ROLES.STUDENT&&s)return{...base,classId:s.classId,...(resource==='Assignment'?{status:'PUBLISHED'}:{}),$or:[{sectionId:s.sectionId},{sectionId:null}]};if(r===ROLES.PARENT)return{...base,classId:{$in:ids(children.map(x=>x.classId))},...(resource==='Assignment'?{status:'PUBLISHED'}:{}),sectionId:{$in:ids(children.map(x=>x.sectionId))}};if(r===ROLES.TEACHER)return{...base,sectionId:{$in:ta.sections}}}if(resource==='Examination'){if(r===ROLES.STUDENT&&s)return{...base,classIds:{$in:[s.classId]}};if(r===ROLES.PARENT)return{...base,classIds:{$in:ids(children.map(x=>x.classId))}};if(r===ROLES.TEACHER)return{...base,classIds:{$in:ta.classes}}}if(resource==='Notice'){const a=r===ROLES.TEACHER?'TEACHER':r===ROLES.STUDENT?'STUDENT':r===ROLES.PARENT?'PARENT':null;if(a)return{...base,audience:{$in:['ALL',a]}}}if(resource==='CalendarEvent'){const a=r===ROLES.TEACHER?'TEACHER':r===ROLES.STUDENT?'STUDENT':r===ROLES.PARENT?'PARENT':null;if(a)return{...base,audience:{$in:['ALL',a]}}}if(resource==='Leave'&&![ROLES.SUPER_ADMIN,ROLES.ADMINISTRATOR,ROLES.SCHOOL_ADMIN].includes(r))return{...base,applicantUserId:req.user._id};return base;}
const schoolFilter=req=>req.user.role===ROLES.SUPER_ADMIN?{}:req.user.role===ROLES.ADMINISTRATOR?{_id:{$in:req.user.assignedSchoolIds||[]}}:{_id:req.user.schoolId};
async function audit(req,action,resource,resourceId,metadata){try{await M.AuditLog.create({schoolId:req.tenantId||req.user?.schoolId,userId:req.user?._id,action,resource,resourceId,metadata,ip:req.ip,userAgent:req.headers['user-agent']})}catch{}}
const validateId=(req,_res,next)=>mongoose.isValidObjectId(req.params.id)?next():next(new ApiError(400,'Invalid id'));
module.exports={ApiError,asyncHandler,success,page,accessToken,refreshToken,verifyRefresh,cookies,setRefreshCookie,clearRefreshCookie,authenticate,allowRoles,permission,tenant,scoped,schoolFilter,audit,validateId,errorHandler,ids,teacherAssignmentIds};
