const express=require('express');
const M=require('../models');const E=require('../models/extended');const C=require('../core');const storage=require('../services/storage.service');const N=require('../services/notification.service');const {ROLES}=require('../constants/roles');const {PERMISSIONS}=require('../constants/permissions');const router=express.Router();
const esc=v=>String(v).replace(/[.*+?^${}()|[\]\\]/g,'\\$&');const base=req=>({schoolId:req.tenantId||req.user.schoolId});
function filters(q,Model){const f={};for(const k of ['status','type','academicSessionId','classId','sectionId','studentId','teacherId','subjectId','examinationId','assignmentId'])if(q[k]&&Model.schema.path(k))f[k]=q[k];if(q.date){const d=new Date(q.date);d.setUTCHours(0,0,0,0);const e=new Date(d);e.setUTCDate(e.getUTCDate()+1);f.date={$gte:d,$lt:e}}return f}
async function list(Model,f,q,populate){const{page,limit,skip}=C.page(q);let query=Model.find(f).sort(q.sort||'-createdAt').skip(skip).limit(limit);if(populate)query=query.populate(populate);const[items,total]=await Promise.all([query.lean(),Model.countDocuments(f)]);return{items,meta:{total,page,limit,pages:Math.ceil(total/limit)}}}
function search(q,fields){return q.search&&fields.length?{$or:fields.map(x=>({[x]:new RegExp(esc(q.search),'i')}))}:{} }
function secureList(path,Model,resource,perm,fields=[]){router.get(path,C.authenticate,C.tenant(true),C.permission(perm),C.asyncHandler(async(req,res)=>{let f={...base(req),...filters(req.query,Model),...search(req.query,fields)};f=C.scoped(req,resource,f);const r=await list(Model,f,req.query);C.success(res,r.items,`${resource} list`,200,r.meta)}));router.get(`${path}/:id`,C.authenticate,C.tenant(true),C.permission(perm),C.validateId,C.asyncHandler(async(req,res)=>{const item=await Model.findOne(C.scoped(req,resource,{...base(req),_id:req.params.id})).lean();if(!item)throw new C.ApiError(404,`${resource} not found`);C.success(res,item)}))}
secureList('/students',M.Student,'Student',PERMISSIONS.STUDENTS_READ,['firstName','lastName','admissionNo','rollNo']);secureList('/academics/classes',M.Class,'Class',PERMISSIONS.ACADEMICS_READ,['name']);secureList('/academics/sections',M.Section,'Section',PERMISSIONS.ACADEMICS_READ,['name','room']);secureList('/academics/subjects',M.Subject,'Subject',PERMISSIONS.ACADEMICS_READ,['name','code']);secureList('/timetable',M.Timetable,'Timetable',PERMISSIONS.TIMETABLE_READ,['day']);secureList('/examinations',M.Examination,'Examination',PERMISSIONS.EXAMS_READ,['name','type']);secureList('/notices',M.Notice,'Notice',PERMISSIONS.NOTICES_READ,['title','body']);secureList('/fees',M.Fee,'Fee',PERMISSIONS.FEES_READ,['name','category']);
router.post('/academics/sessions/:id/make-current',C.authenticate,C.tenant(true),C.permission(PERMISSIONS.ACADEMICS_WRITE),C.validateId,C.asyncHandler(async(req,res)=>{const row=await M.AcademicSession.findOne({_id:req.params.id,schoolId:req.tenantId});if(!row)throw new C.ApiError(404,'Session not found');await M.AcademicSession.updateMany({schoolId:req.tenantId},{$set:{isCurrent:false}});row.isCurrent=true;row.status='ACTIVE';await row.save();C.success(res,row,'Current academic session updated')}));
router.get('/attendance',C.authenticate,C.tenant(true),C.permission(PERMISSIONS.ATTENDANCE_READ),C.asyncHandler(async(req,res)=>{const f=C.scoped(req,'Attendance',{...base(req),...filters(req.query,M.Attendance)});const r=await list(M.Attendance,f,req.query);C.success(res,r.items,'Attendance list',200,r.meta)}));
router.post('/attendance/bulk',C.authenticate,C.tenant(true),C.permission(PERMISSIONS.ATTENDANCE_WRITE),C.asyncHandler(async(req,res)=>{const{academicSessionId,date,classId,sectionId,records=[]}=req.body;if(!academicSessionId||!date||!classId||!sectionId||!Array.isArray(records))throw new C.ApiError(400,'session, date, class, section and records are required');if(req.user.role===ROLES.TEACHER){const assigned=(req.teacherProfile?.classAssignments||[]).some(x=>String(x.classId)===String(classId)&&String(x.sectionId)===String(sectionId));if(!assigned)throw new C.ApiError(403,'Class/section is not assigned to this teacher')}const d=new Date(date);d.setUTCHours(0,0,0,0);const ops=records.map(x=>({updateOne:{filter:{schoolId:req.tenantId,academicSessionId,date:d,studentId:x.studentId},update:{$set:{classId,sectionId,status:x.status,remarks:x.remarks,markedBy:req.user._id}},upsert:true}}));if(ops.length)await M.Attendance.bulkWrite(ops,{ordered:false});const absent=records.filter(x=>['ABSENT','LATE'].includes(x.status)).map(x=>x.studentId);if(absent.length)await N.notifyParentsForStudents(absent,{schoolId:req.tenantId,title:'Attendance update',message:'Your child attendance has been updated.',type:'ATTENDANCE',link:'/parent/attendance'});await C.audit(req,'BULK_MARK','Attendance',null,{date,count:records.length});C.success(res,{count:records.length},'Attendance saved')}));
router.get('/assignments',C.authenticate,C.tenant(true),C.permission(PERMISSIONS.ASSIGNMENTS_READ),C.asyncHandler(async(req,res)=>{const f=C.scoped(req,'Assignment',{...base(req),...filters(req.query,M.Assignment),...search(req.query,['title','description'])});const r=await list(M.Assignment,f,req.query);C.success(res,r.items,'Assignments list',200,r.meta)}));
router.post('/assignments',C.authenticate,C.tenant(true),C.permission(PERMISSIONS.ASSIGNMENTS_WRITE),C.asyncHandler(async(req,res)=>{const data={...req.body,schoolId:req.tenantId};if(req.user.role===ROLES.TEACHER){data.teacherId=req.teacherProfile?._id;const a=req.teacherProfile?.classAssignments||[];if(!a.some(x=>String(x.classId)===String(data.classId)&&(!data.sectionId||String(x.sectionId)===String(data.sectionId))))throw new C.ApiError(403,'Assignment target is outside your allocation')}C.success(res,await M.Assignment.create(data),'Assignment created',201)}));
router.patch('/assignments/:id',C.authenticate,C.tenant(true),C.permission(PERMISSIONS.ASSIGNMENTS_WRITE),C.validateId,C.asyncHandler(async(req,res)=>{const f={_id:req.params.id,...base(req)};if(req.user.role===ROLES.TEACHER)f.teacherId=req.teacherProfile?._id;const item=await M.Assignment.findOneAndUpdate(f,req.body,{new:true,runValidators:true});if(!item)throw new C.ApiError(404,'Assignment not found');C.success(res,item)}));
router.delete('/assignments/:id',C.authenticate,C.tenant(true),C.permission(PERMISSIONS.ASSIGNMENTS_WRITE),C.validateId,C.asyncHandler(async(req,res)=>{const f={_id:req.params.id,...base(req)};if(req.user.role===ROLES.TEACHER)f.teacherId=req.teacherProfile?._id;const item=await M.Assignment.findOneAndDelete(f);if(!item)throw new C.ApiError(404,'Assignment not found');C.success(res,null,'Assignment deleted')}));
router.get('/assignments/:id/submissions',C.authenticate,C.tenant(true),C.permission(PERMISSIONS.ASSIGNMENTS_WRITE),C.validateId,C.asyncHandler(async(req,res)=>{const a=await M.Assignment.findOne(C.scoped(req,'Assignment',{_id:req.params.id,...base(req)}));if(!a)throw new C.ApiError(404,'Assignment not found');C.success(res,await E.AssignmentSubmission.find({schoolId:req.tenantId,assignmentId:a._id}).populate('studentId','firstName lastName admissionNo').lean())}));
router.get('/assignment-submissions/me',C.authenticate,C.tenant(true),C.allowRoles(ROLES.STUDENT),C.asyncHandler(async(req,res)=>C.success(res,await E.AssignmentSubmission.find({schoolId:req.tenantId,studentId:req.studentProfile?._id}).sort('-submittedAt').lean())));
router.post('/assignments/:id/submit',C.authenticate,C.tenant(true),C.allowRoles(ROLES.STUDENT),C.validateId,C.asyncHandler(async(req,res)=>{const a=await M.Assignment.findOne(C.scoped(req,'Assignment',{_id:req.params.id,...base(req)}));if(!a||a.status!=='PUBLISHED')throw new C.ApiError(404,'Published assignment not found');const late=a.dueAt&&new Date()>a.dueAt;const row=await E.AssignmentSubmission.findOneAndUpdate({assignmentId:a._id,studentId:req.studentProfile._id},{$set:{schoolId:req.tenantId,text:req.body.text,attachments:req.body.attachments||[],submittedAt:new Date(),status:late?'LATE':'SUBMITTED'}},{new:true,upsert:true,runValidators:true});C.success(res,row,'Assignment submitted')}));
router.patch('/assignment-submissions/:id/review',C.authenticate,C.tenant(true),C.permission(PERMISSIONS.ASSIGNMENTS_WRITE),C.validateId,C.asyncHandler(async(req,res)=>{const row=await E.AssignmentSubmission.findOneAndUpdate({_id:req.params.id,schoolId:req.tenantId},{$set:{marks:req.body.marks,remarks:req.body.remarks,status:'REVIEWED',reviewedBy:req.user._id,reviewedAt:new Date()}},{new:true});if(!row)throw new C.ApiError(404,'Submission not found');C.success(res,row,'Submission reviewed')}));
router.get('/results',C.authenticate,C.tenant(true),C.permission(PERMISSIONS.RESULTS_READ),C.asyncHandler(async(req,res)=>{let f=C.scoped(req,'Result',{...base(req),...filters(req.query,M.Result)});if([ROLES.STUDENT,ROLES.PARENT].includes(req.user.role))f.published=true;const r=await list(M.Result,f,req.query);C.success(res,r.items,'Results list',200,r.meta)}));
router.post('/results',C.authenticate,C.tenant(true),C.permission(PERMISSIONS.RESULTS_WRITE),C.asyncHandler(async(req,res)=>{if(req.user.role===ROLES.TEACHER&&!C.teacherAssignmentIds(req.teacherProfile).sections.includes(String(req.body.sectionId)))throw new C.ApiError(403,'Section is not assigned');C.success(res,await M.Result.create({...req.body,schoolId:req.tenantId,enteredBy:req.user._id}),'Result saved',201)}));
router.patch('/results/:id',C.authenticate,C.tenant(true),C.permission(PERMISSIONS.RESULTS_WRITE),C.validateId,C.asyncHandler(async(req,res)=>{const row=await M.Result.findOneAndUpdate(C.scoped(req,'Result',{_id:req.params.id,...base(req)}),req.body,{new:true,runValidators:true});if(!row)throw new C.ApiError(404,'Result not found');C.success(res,row)}));
router.post('/results/:id/publish',C.authenticate,C.tenant(true),C.permission(PERMISSIONS.RESULTS_WRITE),C.validateId,C.asyncHandler(async(req,res)=>{const row=await M.Result.findOneAndUpdate({_id:req.params.id,...base(req)},{published:true},{new:true});if(!row)throw new C.ApiError(404,'Result not found');const student=await M.Student.findById(row.studentId).lean(),users=[student?.userId];if(student?.parentIds?.length)users.push(...await M.Parent.find({_id:{$in:student.parentIds}}).distinct('userId'));await N.notifyUsers(users,{schoolId:req.tenantId,title:'Result published',message:'A new examination result is available.',type:'RESULT',link:'/student/results'});C.success(res,row,'Result published')}));
router.get('/fees-payments',C.authenticate,C.tenant(true),C.permission(PERMISSIONS.FEES_READ),C.asyncHandler(async(req,res)=>{const r=await list(M.Payment,C.scoped(req,'Payment',{...base(req),...filters(req.query,M.Payment)}),req.query);C.success(res,r.items,'Payments list',200,r.meta)}));
router.get('/leaves',C.authenticate,C.tenant(true),C.permission(PERMISSIONS.LEAVES_READ),C.asyncHandler(async(req,res)=>{let f=base(req);if(![ROLES.SUPER_ADMIN,ROLES.ADMINISTRATOR,ROLES.SCHOOL_ADMIN].includes(req.user.role))f=C.scoped(req,'Leave',f);const r=await list(M.Leave,f,req.query);C.success(res,r.items,'Leaves list',200,r.meta)}));
router.post('/leaves',C.authenticate,C.tenant(true),C.permission(PERMISSIONS.LEAVES_WRITE),C.asyncHandler(async(req,res)=>{const studentId=req.user.role===ROLES.STUDENT?req.studentProfile?._id:req.body.studentId;C.success(res,await M.Leave.create({...req.body,schoolId:req.tenantId,studentId,applicantUserId:req.user._id}),'Leave requested',201)}));
router.post('/leaves/:id/review',C.authenticate,C.tenant(true),C.allowRoles(ROLES.SUPER_ADMIN,ROLES.ADMINISTRATOR,ROLES.SCHOOL_ADMIN),C.validateId,C.asyncHandler(async(req,res)=>{const status=String(req.body.status||'').toUpperCase();if(!['APPROVED','REJECTED'].includes(status))throw new C.ApiError(400,'status must be APPROVED or REJECTED');const row=await M.Leave.findOneAndUpdate({_id:req.params.id,...base(req)},{status,reviewedBy:req.user._id,reviewNote:req.body.reviewNote},{new:true});if(!row)throw new C.ApiError(404,'Leave not found');await N.notifyUsers([row.applicantUserId],{schoolId:req.tenantId,title:'Leave request updated',message:`Your leave request is ${status.toLowerCase()}.`,type:'LEAVE'});C.success(res,row,'Leave reviewed')}));
router.get('/calendar',C.authenticate,C.tenant(true),C.asyncHandler(async(req,res)=>{const r=await list(E.CalendarEvent,C.scoped(req,'CalendarEvent',{...base(req),...filters(req.query,E.CalendarEvent)}),req.query);C.success(res,r.items,'Calendar list',200,r.meta)}));
router.post('/calendar',C.authenticate,C.tenant(true),C.permission(PERMISSIONS.ACADEMICS_WRITE),C.asyncHandler(async(req,res)=>{const row=await E.CalendarEvent.create({...req.body,schoolId:req.tenantId,createdBy:req.user._id});await N.notifyAudience({schoolId:req.tenantId,audience:row.audience,title:row.title,message:row.description||'New calendar event',type:'CALENDAR',link:'/student/calendar'});C.success(res,row,'Event created',201)}));
router.patch('/calendar/:id',C.authenticate,C.tenant(true),C.permission(PERMISSIONS.ACADEMICS_WRITE),C.validateId,C.asyncHandler(async(req,res)=>{const row=await E.CalendarEvent.findOneAndUpdate({_id:req.params.id,...base(req)},req.body,{new:true,runValidators:true});if(!row)throw new C.ApiError(404,'Event not found');C.success(res,row)}));
router.delete('/calendar/:id',C.authenticate,C.tenant(true),C.permission(PERMISSIONS.ACADEMICS_WRITE),C.validateId,C.asyncHandler(async(req,res)=>{await E.CalendarEvent.findOneAndDelete({_id:req.params.id,...base(req)});C.success(res,null,'Event deleted')}));
router.get('/certificates',C.authenticate,C.tenant(true),C.asyncHandler(async(req,res)=>{const r=await list(E.Certificate,C.scoped(req,'Certificate',{...base(req),...filters(req.query,E.Certificate)}),req.query);C.success(res,r.items,'Certificates list',200,r.meta)}));
router.post('/certificates',C.authenticate,C.tenant(true),C.asyncHandler(async(req,res)=>{let studentId=req.body.studentId;if(req.user.role===ROLES.STUDENT)studentId=req.studentProfile?._id;if(req.user.role===ROLES.PARENT&&!C.ids(req.parentProfile?.studentIds||[]).includes(String(studentId)))throw new C.ApiError(403,'Child is not linked');if(!studentId)throw new C.ApiError(400,'studentId is required');C.success(res,await E.Certificate.create({schoolId:req.tenantId,studentId,type:req.body.type,reason:req.body.reason,requestedBy:req.user._id}),'Certificate requested',201)}));
router.post('/certificates/:id/review',C.authenticate,C.tenant(true),C.allowRoles(ROLES.SUPER_ADMIN,ROLES.ADMINISTRATOR,ROLES.SCHOOL_ADMIN),C.validateId,C.asyncHandler(async(req,res)=>{const status=String(req.body.status||'').toUpperCase();if(!['APPROVED','ISSUED','REJECTED'].includes(status))throw new C.ApiError(400,'Invalid status');const set={status,reviewedBy:req.user._id,reviewNote:req.body.reviewNote};if(req.body.fileUrl)set.fileUrl=req.body.fileUrl;if(req.body.certificateNo)set.certificateNo=req.body.certificateNo;if(status==='ISSUED')set.issuedAt=new Date();const row=await E.Certificate.findOneAndUpdate({_id:req.params.id,...base(req)},{$set:set},{new:true});if(!row)throw new C.ApiError(404,'Certificate not found');if(status==='ISSUED'&&row.type==='TRANSFER_CERTIFICATE')await M.Student.updateOne({_id:row.studentId,schoolId:req.tenantId},{$set:{status:'TRANSFERRED'}});C.success(res,row,'Certificate updated')}));
router.post('/uploads',C.authenticate,C.tenant(false),C.asyncHandler(async(req,res)=>{const file=await storage.saveBase64(req.body);const host=file.url.startsWith('http')?'':`${req.protocol}://${req.get('host')}`;C.success(res,{...file,url:`${host}${file.url}`},'File uploaded',201)}));
router.delete('/uploads/:name',C.authenticate,C.asyncHandler(async(req,res)=>{await storage.remove(req.params.name);C.success(res,null,'File removed')}));
router.get('/notifications',C.authenticate,C.asyncHandler(async(req,res)=>C.success(res,await M.Notification.find({userId:req.user._id}).sort('-createdAt').limit(50).lean())));
router.patch('/notifications/:id/read',C.authenticate,C.validateId,C.asyncHandler(async(req,res)=>{const row=await M.Notification.findOneAndUpdate({_id:req.params.id,userId:req.user._id},{readAt:new Date()},{new:true});if(!row)throw new C.ApiError(404,'Notification not found');C.success(res,row)}));router.post('/notifications/read-all',C.authenticate,C.asyncHandler(async(req,res)=>{await M.Notification.updateMany({userId:req.user._id,readAt:null},{readAt:new Date()});C.success(res,null,'Notifications marked read')}));
module.exports=router;
