const express=require('express');
const mongoose=require('mongoose');
const M=require('../models');
const {ROLES}=require('../constants/roles');
const {PERMISSIONS}=require('../constants/permissions');
const C=require('../core');
const router=express.Router();
const esc=v=>String(v).replace(/[.*+?^${}()|[\]\\]/g,'\\$&');
const searchFilter=(q,fields)=>q.search&&fields?.length?{$or:fields.map(f=>({[f]:new RegExp(esc(q.search),'i')}))}:{};
const tenantBase=req=>req.user.role===ROLES.SUPER_ADMIN?(req.tenantId?{schoolId:req.tenantId}:{}):{schoolId:req.tenantId||req.user.schoolId};
async function list(Model,filter,q){const {page,limit,skip}=C.page(q);const total=await Model.countDocuments(filter);const items=await Model.find(filter).sort(q.sort||'-createdAt').skip(skip).limit(limit).lean();return{items,meta:{total,page,limit,pages:Math.ceil(total/limit)}}}
function payload(req,resource){const p={...req.body};if(req.tenantId&&resource!=='School'&&resource!=='Administrator')p.schoolId=req.tenantId;if(resource==='Attendance')p.markedBy=req.user._id;if(resource==='Assignment'&&req.teacherProfile)p.teacherId=req.teacherProfile._id;if(resource==='Notice')p.createdBy=req.user._id;if(resource==='Leave')p.applicantUserId=req.user._id;if(resource==='Result')p.enteredBy=req.user._id;if(resource==='Payment')p.receivedBy=req.user._id;return p}
function crud(path,Model,resource,readPerm,writePerm,{tenantScoped=true,search=[]}={}){
  const base=tenantScoped?[C.authenticate,C.tenant(true)]:[C.authenticate];
  router.get(path,...base,C.permission(readPerm),C.asyncHandler(async(req,res)=>{let f=tenantScoped?tenantBase(req):{};f=C.scoped(req,resource,{...f,...searchFilter(req.query,search)});const r=await list(Model,f,req.query);C.success(res,r.items,`${resource} list`,200,r.meta)}));
  router.get(`${path}/:id`,...base,C.permission(readPerm),C.validateId,C.asyncHandler(async(req,res)=>{let f=tenantScoped?tenantBase(req):{};f=C.scoped(req,resource,{...f,_id:req.params.id});const item=await Model.findOne(f).lean();if(!item)throw new C.ApiError(404,`${resource} not found`);C.success(res,item)}));
  router.post(path,...base,C.permission(writePerm),C.asyncHandler(async(req,res)=>{const item=await Model.create(payload(req,resource));await C.audit(req,'CREATE',resource,item._id);C.success(res,item,`${resource} created`,201)}));
  router.patch(`${path}/:id`,...base,C.permission(writePerm),C.validateId,C.asyncHandler(async(req,res)=>{let f=tenantScoped?tenantBase(req):{};f=C.scoped(req,resource,{...f,_id:req.params.id});const item=await Model.findOneAndUpdate(f,payload(req,resource),{new:true,runValidators:true});if(!item)throw new C.ApiError(404,`${resource} not found`);await C.audit(req,'UPDATE',resource,item._id);C.success(res,item)}));
  router.delete(`${path}/:id`,...base,C.permission(writePerm),C.validateId,C.asyncHandler(async(req,res)=>{let f=tenantScoped?tenantBase(req):{};f=C.scoped(req,resource,{...f,_id:req.params.id});const item=await Model.findOneAndDelete(f);if(!item)throw new C.ApiError(404,`${resource} not found`);await C.audit(req,'DELETE',resource,item._id);C.success(res,null,`${resource} deleted`)}));
}

router.post('/auth/login',C.asyncHandler(async(req,res)=>{const{email,password}=req.body;if(!email||!password)throw new C.ApiError(400,'email and password are required');const u=await M.User.findOne({email:String(email).toLowerCase()}).select('+password +refreshTokenHash');if(!u||!(await u.comparePassword(password)))throw new C.ApiError(401,'Invalid email or password');if(u.status!=='ACTIVE')throw new C.ApiError(403,'Account is not active');u.lastLoginAt=new Date();const accessToken=C.accessToken(u),refreshToken=C.refreshToken(u);await u.setRefreshToken(refreshToken);await u.save({validateBeforeSave:false});C.success(res,{user:u.toJSON(),accessToken,refreshToken},'Login successful')}));
router.post('/auth/refresh',C.asyncHandler(async(req,res)=>{const token=req.body.refreshToken;if(!token)throw new C.ApiError(400,'refreshToken is required');let d;try{d=C.verifyRefresh(token)}catch{throw new C.ApiError(401,'Invalid refresh token')}const u=await M.User.findById(d.sub).select('+refreshTokenHash');if(!u||!(await u.compareRefreshToken(token)))throw new C.ApiError(401,'Refresh token is no longer valid');const accessToken=C.accessToken(u),refreshToken=C.refreshToken(u);await u.setRefreshToken(refreshToken);await u.save({validateBeforeSave:false});C.success(res,{accessToken,refreshToken})}));
router.get('/auth/me',C.authenticate,(req,res)=>C.success(res,req.user));
router.post('/auth/logout',C.authenticate,C.asyncHandler(async(req,res)=>{await M.User.findByIdAndUpdate(req.user._id,{$unset:{refreshTokenHash:1}});await C.audit(req,'LOGOUT','Auth',req.user._id);C.success(res,null,'Logged out')}));
router.post('/auth/change-password',C.authenticate,C.asyncHandler(async(req,res)=>{const{currentPassword,newPassword}=req.body;if(!currentPassword||!newPassword||String(newPassword).length<8)throw new C.ApiError(400,'Valid currentPassword and newPassword are required');const u=await M.User.findById(req.user._id).select('+password');if(!(await u.comparePassword(currentPassword)))throw new C.ApiError(401,'Current password is incorrect');u.password=newPassword;u.refreshTokenHash=undefined;await u.save();C.success(res,null,'Password changed')}));

router.get('/schools',C.authenticate,C.permission(PERMISSIONS.SCHOOLS_READ),C.asyncHandler(async(req,res)=>{const r=await list(M.School,{...C.schoolFilter(req),...searchFilter(req.query,['name','code','slug','email'])},req.query);C.success(res,r.items,'Schools list',200,r.meta)}));
router.get('/schools/:id',C.authenticate,C.permission(PERMISSIONS.SCHOOLS_READ),C.validateId,C.asyncHandler(async(req,res)=>{const item=await M.School.findOne({_id:req.params.id,...C.schoolFilter(req)}).lean();if(!item)throw new C.ApiError(404,'School not found');C.success(res,item)}));
router.post('/schools',C.authenticate,C.allowRoles(ROLES.SUPER_ADMIN),C.asyncHandler(async(req,res)=>{const item=await M.School.create({...req.body,createdBy:req.user._id});await C.audit(req,'CREATE','School',item._id);C.success(res,item,'School created',201)}));
router.patch('/schools/:id',C.authenticate,C.permission(PERMISSIONS.SCHOOLS_WRITE),C.validateId,C.asyncHandler(async(req,res)=>{const item=await M.School.findOneAndUpdate({_id:req.params.id,...C.schoolFilter(req)},req.body,{new:true,runValidators:true});if(!item)throw new C.ApiError(404,'School not found');await C.audit(req,'UPDATE','School',item._id);C.success(res,item)}));
router.delete('/schools/:id',C.authenticate,C.allowRoles(ROLES.SUPER_ADMIN),C.validateId,C.asyncHandler(async(req,res)=>{const item=await M.School.findByIdAndDelete(req.params.id);if(!item)throw new C.ApiError(404,'School not found');await C.audit(req,'DELETE','School',item._id);C.success(res,null,'School deleted')}));

router.get('/users',C.authenticate,C.tenant(false),C.permission(PERMISSIONS.USERS_READ),C.asyncHandler(async(req,res)=>{const f=req.user.role===ROLES.SUPER_ADMIN?(req.tenantId?{schoolId:req.tenantId}:{}):tenantBase(req);const r=await list(M.User,{...f,...searchFilter(req.query,['name','email','role'])},req.query);C.success(res,r.items,'Users list',200,r.meta)}));
router.post('/users',C.authenticate,C.tenant(false),C.permission(PERMISSIONS.USERS_WRITE),C.asyncHandler(async(req,res)=>{const role=req.body.role;const allowed=req.user.role===ROLES.SUPER_ADMIN||req.user.role===ROLES.ADMINISTRATOR&&[ROLES.SCHOOL_ADMIN,ROLES.TEACHER,ROLES.STUDENT,ROLES.PARENT].includes(role)||req.user.role===ROLES.SCHOOL_ADMIN&&[ROLES.TEACHER,ROLES.STUDENT,ROLES.PARENT].includes(role);if(!allowed)throw new C.ApiError(403,'You cannot assign this role');if(!req.body.password)throw new C.ApiError(400,'password is required');const data={...req.body};if(req.user.role!==ROLES.SUPER_ADMIN)data.schoolId=req.tenantId;const item=await M.User.create(data);await C.audit(req,'CREATE','User',item._id);C.success(res,item,'User created',201)}));
router.patch('/users/:id',C.authenticate,C.tenant(false),C.permission(PERMISSIONS.USERS_WRITE),C.validateId,C.asyncHandler(async(req,res)=>{const f=req.user.role===ROLES.SUPER_ADMIN?{_id:req.params.id}:{_id:req.params.id,...tenantBase(req)};const data={...req.body};delete data.password;delete data.refreshTokenHash;const item=await M.User.findOneAndUpdate(f,data,{new:true,runValidators:true});if(!item)throw new C.ApiError(404,'User not found');C.success(res,item)}));

crud('/administrators',M.Administrator,'Administrator',PERMISSIONS.USERS_READ,PERMISSIONS.USERS_WRITE,{tenantScoped:false,search:['designation','employeeCode']});
crud('/academics/sessions',M.AcademicSession,'AcademicSession',PERMISSIONS.ACADEMICS_READ,PERMISSIONS.ACADEMICS_WRITE,{search:['name','status']});
crud('/academics/classes',M.Class,'Class',PERMISSIONS.ACADEMICS_READ,PERMISSIONS.ACADEMICS_WRITE,{search:['name','status']});
crud('/academics/sections',M.Section,'Section',PERMISSIONS.ACADEMICS_READ,PERMISSIONS.ACADEMICS_WRITE,{search:['name','room','status']});
crud('/academics/subjects',M.Subject,'Subject',PERMISSIONS.ACADEMICS_READ,PERMISSIONS.ACADEMICS_WRITE,{search:['name','code','type']});
crud('/students',M.Student,'Student',PERMISSIONS.STUDENTS_READ,PERMISSIONS.STUDENTS_WRITE,{search:['firstName','lastName','admissionNo','rollNo']});
crud('/parents',M.Parent,'Parent',PERMISSIONS.STUDENTS_READ,PERMISSIONS.STUDENTS_WRITE,{search:['name','phone','email']});
crud('/teachers',M.Teacher,'Teacher',PERMISSIONS.TEACHERS_READ,PERMISSIONS.TEACHERS_WRITE,{search:['name','employeeCode','email','department']});
crud('/timetable',M.Timetable,'Timetable',PERMISSIONS.TIMETABLE_READ,PERMISSIONS.TIMETABLE_WRITE,{search:['day']});
crud('/assignments',M.Assignment,'Assignment',PERMISSIONS.ASSIGNMENTS_READ,PERMISSIONS.ASSIGNMENTS_WRITE,{search:['title','description','type']});
crud('/examinations',M.Examination,'Examination',PERMISSIONS.EXAMS_READ,PERMISSIONS.EXAMS_WRITE,{search:['name','type']});
crud('/notices',M.Notice,'Notice',PERMISSIONS.NOTICES_READ,PERMISSIONS.NOTICES_WRITE,{search:['title','body','priority']});

router.get('/attendance',C.authenticate,C.tenant(true),C.permission(PERMISSIONS.ATTENDANCE_READ),C.asyncHandler(async(req,res)=>{const f=C.scoped(req,'Attendance',{...tenantBase(req),...searchFilter(req.query,['status'])});const r=await list(M.Attendance,f,req.query);C.success(res,r.items,'Attendance list',200,r.meta)}));
router.post('/attendance/bulk',C.authenticate,C.tenant(true),C.permission(PERMISSIONS.ATTENDANCE_WRITE),C.asyncHandler(async(req,res)=>{const{academicSessionId,date,classId,sectionId,records=[]}=req.body;if(!academicSessionId||!date||!classId||!sectionId||!Array.isArray(records))throw new C.ApiError(400,'academicSessionId, date, classId, sectionId and records are required');const d=new Date(date);d.setHours(0,0,0,0);const ops=records.map(x=>({updateOne:{filter:{schoolId:req.tenantId,academicSessionId,date:d,studentId:x.studentId},update:{$set:{classId,sectionId,status:x.status,remarks:x.remarks,markedBy:req.user._id}},upsert:true}}));const out=ops.length?await M.Attendance.bulkWrite(ops,{ordered:false}):{};await C.audit(req,'BULK_MARK','Attendance',undefined,{date,count:records.length});C.success(res,out,'Attendance saved')}));

router.get('/results',C.authenticate,C.tenant(true),C.permission(PERMISSIONS.RESULTS_READ),C.asyncHandler(async(req,res)=>{const f=C.scoped(req,'Result',tenantBase(req));const r=await list(M.Result,f,req.query);C.success(res,r.items,'Results list',200,r.meta)}));
router.post('/results',C.authenticate,C.tenant(true),C.permission(PERMISSIONS.RESULTS_WRITE),C.asyncHandler(async(req,res)=>{const item=await M.Result.create(payload(req,'Result'));await C.audit(req,'CREATE','Result',item._id);C.success(res,item,'Result saved',201)}));
router.patch('/results/:id',C.authenticate,C.tenant(true),C.permission(PERMISSIONS.RESULTS_WRITE),C.validateId,C.asyncHandler(async(req,res)=>{const data=payload(req,'Result');if(data.marks){data.totalObtained=data.marks.reduce((s,x)=>s+Number(x.marksObtained||0),0);data.totalMax=data.marks.reduce((s,x)=>s+Number(x.maxMarks||0),0);data.percentage=data.totalMax?Number(((data.totalObtained/data.totalMax)*100).toFixed(2)):0}const f=C.scoped(req,'Result',{...tenantBase(req),_id:req.params.id});const item=await M.Result.findOneAndUpdate(f,data,{new:true,runValidators:true});if(!item)throw new C.ApiError(404,'Result not found');C.success(res,item)}));
router.post('/results/:id/publish',C.authenticate,C.tenant(true),C.permission(PERMISSIONS.RESULTS_WRITE),C.validateId,C.asyncHandler(async(req,res)=>{const item=await M.Result.findOneAndUpdate(C.scoped(req,'Result',{...tenantBase(req),_id:req.params.id}),{published:true},{new:true});if(!item)throw new C.ApiError(404,'Result not found');await C.audit(req,'PUBLISH','Result',item._id);C.success(res,item,'Result published')}));

crud('/fees',M.Fee,'Fee',PERMISSIONS.FEES_READ,PERMISSIONS.FEES_WRITE,{search:['name','category']});
router.get('/fees-payments',C.authenticate,C.tenant(true),C.permission(PERMISSIONS.FEES_READ),C.asyncHandler(async(req,res)=>{const r=await list(M.Payment,C.scoped(req,'Payment',tenantBase(req)),req.query);C.success(res,r.items,'Payments list',200,r.meta)}));
router.post('/fees-payments',C.authenticate,C.tenant(true),C.permission(PERMISSIONS.FEES_WRITE),C.asyncHandler(async(req,res)=>{const item=await M.Payment.create(payload(req,'Payment'));await C.audit(req,'PAYMENT_RECEIVED','Payment',item._id,{amount:item.amount,receiptNo:item.receiptNo});C.success(res,item,'Payment recorded',201)}));

router.get('/leaves',C.authenticate,C.tenant(true),C.permission(PERMISSIONS.LEAVES_READ),C.asyncHandler(async(req,res)=>{const r=await list(M.Leave,C.scoped(req,'Leave',tenantBase(req)),req.query);C.success(res,r.items,'Leaves list',200,r.meta)}));
router.post('/leaves',C.authenticate,C.tenant(true),C.permission(PERMISSIONS.LEAVES_WRITE),C.asyncHandler(async(req,res)=>{const item=await M.Leave.create(payload(req,'Leave'));await C.audit(req,'CREATE','Leave',item._id);C.success(res,item,'Leave requested',201)}));
router.post('/leaves/:id/review',C.authenticate,C.tenant(true),C.allowRoles(ROLES.SUPER_ADMIN,ROLES.ADMINISTRATOR,ROLES.SCHOOL_ADMIN),C.validateId,C.asyncHandler(async(req,res)=>{const status=String(req.body.status||'').toUpperCase();if(!['APPROVED','REJECTED'].includes(status))throw new C.ApiError(400,'status must be APPROVED or REJECTED');const item=await M.Leave.findOneAndUpdate({...tenantBase(req),_id:req.params.id},{status,reviewedBy:req.user._id,reviewNote:req.body.reviewNote},{new:true});if(!item)throw new C.ApiError(404,'Leave not found');C.success(res,item,'Leave reviewed')}));

router.get('/notifications',C.authenticate,C.tenant(false),C.asyncHandler(async(req,res)=>{const r=await list(M.Notification,{userId:req.user._id},req.query);C.success(res,r.items,'Notifications',200,r.meta)}));
router.post('/notifications/:id/read',C.authenticate,C.validateId,C.asyncHandler(async(req,res)=>{const item=await M.Notification.findOneAndUpdate({_id:req.params.id,userId:req.user._id},{readAt:new Date()},{new:true});if(!item)throw new C.ApiError(404,'Notification not found');C.success(res,item)}));

router.get('/reports/dashboard',C.authenticate,C.tenant(false),C.permission(PERMISSIONS.REPORTS_READ),C.asyncHandler(async(req,res)=>{const sid=req.user.role===ROLES.SUPER_ADMIN?req.tenantId:(req.tenantId||req.user.schoolId);const scoped=sid?{schoolId:new mongoose.Types.ObjectId(String(sid))}:{};const [schools,users,students,teachers,total,present,revenue]=await Promise.all([M.School.countDocuments(sid?{_id:scoped.schoolId}:{}),M.User.countDocuments(scoped),M.Student.countDocuments({...scoped,status:'ACTIVE'}),M.Teacher.countDocuments({...scoped,status:'ACTIVE'}),M.Attendance.countDocuments(scoped),M.Attendance.countDocuments({...scoped,status:'PRESENT'}),M.Payment.aggregate([{$match:{...scoped,status:'SUCCESS'}},{$group:{_id:null,total:{$sum:'$amount'},transactions:{$sum:1}}}])]);C.success(res,{schools,users,students,teachers,attendanceRate:total?Number(((present/total)*100).toFixed(2)):0,revenue:revenue[0]?.total||0,paymentTransactions:revenue[0]?.transactions||0})}));
router.get('/audit',C.authenticate,C.tenant(false),C.permission(PERMISSIONS.AUDIT_READ),C.asyncHandler(async(req,res)=>{const f=req.user.role===ROLES.SUPER_ADMIN&&!req.tenantId?{}:tenantBase(req);const r=await list(M.AuditLog,f,req.query);C.success(res,r.items,'Audit logs',200,r.meta)}));

module.exports=router;
