const express=require('express');
const crypto=require('crypto');
const M=require('../models');
const E=require('../models/extended');
const C=require('../core');
const config=require('../config/env');
const {ROLES}=require('../constants/roles');
const router=express.Router();
const hash=t=>crypto.createHash('sha256').update(t).digest('hex');
const expiry=()=>new Date(Date.now()+7*24*60*60*1000);
async function issue(req,res,u){const accessToken=C.accessToken(u),refreshToken=C.refreshToken(u);await E.AuthSession.deleteMany({userId:u._id});await E.AuthSession.create({userId:u._id,tokenHash:hash(refreshToken),expiresAt:expiry(),ip:req.ip,userAgent:req.headers['user-agent']});C.setRefreshCookie(res,refreshToken);return{accessToken,refreshToken}}
router.post('/auth/login',C.asyncHandler(async(req,res)=>{const email=String(req.body.email||'').trim().toLowerCase(),password=String(req.body.password||'');if(!email||!password)throw new C.ApiError(400,'email and password are required');const u=await M.User.findOne({email}).select('+password');if(!u||!(await u.comparePassword(password)))throw new C.ApiError(401,'Invalid email or password');if(u.status!=='ACTIVE')throw new C.ApiError(403,'Account is not active');u.lastLoginAt=new Date();await u.save({validateBeforeSave:false});const tokens=await issue(req,res,u);C.success(res,{user:u.toJSON(),accessToken:tokens.accessToken},'Login successful')}));
router.post('/auth/refresh',C.asyncHandler(async(req,res)=>{const token=C.cookies(req)[config.cookieName]||req.body.refreshToken;if(!token)throw new C.ApiError(401,'Refresh token required');let d;try{d=C.verifyRefresh(token)}catch{throw new C.ApiError(401,'Invalid refresh token')}const session=await E.AuthSession.findOne({userId:d.sub,tokenHash:hash(token)});if(!session)throw new C.ApiError(401,'Refresh session expired');const u=await M.User.findById(d.sub);if(!u||u.status!=='ACTIVE')throw new C.ApiError(401,'Account unavailable');await session.deleteOne();const tokens=await issue(req,res,u);C.success(res,{accessToken:tokens.accessToken},'Session refreshed')}));
router.get('/auth/me',C.authenticate,C.asyncHandler(async(req,res)=>{let profile=null;if(req.user.role===ROLES.STUDENT)profile=req.studentProfile;if(req.user.role===ROLES.PARENT)profile=req.parentProfile;if(req.user.role===ROLES.TEACHER)profile=req.teacherProfile;let schools=[];if(req.user.role===ROLES.SUPER_ADMIN)schools=await M.School.find({}).select('name code status settings').lean();else if(req.user.role===ROLES.ADMINISTRATOR)schools=await M.School.find({_id:{$in:req.user.assignedSchoolIds||[]}}).select('name code status settings').lean();else if(req.user.schoolId){const s=await M.School.findById(req.user.schoolId).select('name code status settings').lean();if(s)schools=[s]}C.success(res,{user:req.user.toJSON(),profile,schools})}));
router.post('/auth/logout',C.authenticate,C.asyncHandler(async(req,res)=>{await E.AuthSession.deleteMany({userId:req.user._id});C.clearRefreshCookie(res);await C.audit(req,'LOGOUT','Auth',req.user._id);C.success(res,null,'Logged out')}));
router.post('/auth/change-password',C.authenticate,C.asyncHandler(async(req,res)=>{const current=String(req.body.currentPassword||''),next=String(req.body.newPassword||'');if(next.length<8)throw new C.ApiError(400,'newPassword must be at least 8 characters');const u=await M.User.findById(req.user._id).select('+password');if(!(await u.comparePassword(current)))throw new C.ApiError(401,'Current password is incorrect');u.password=next;await u.save();await E.AuthSession.deleteMany({userId:u._id});C.clearRefreshCookie(res);C.success(res,null,'Password changed')}));
module.exports=router;
